### ISSUE TITLE
Not working with xcode 7 

### ISSUE THREAD

**Issue by Hastewave** [CFKevinRef/KCOrderedAccessorFix#13]
Fix not working with new xcode 7 core data generators
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Unacceptable type of value for ordered to-many relationship: property = "XXXXX"; desired type = NSOrderedSet

**Comment by CFKevinRef** [comment]
Can you tell which accessor/pattern was causing this exception?

The exception may also include "given type" and "value" as well as a stack trace. All of that information will be helpful.

**Comment by CFKevinRef** [comment]
Going to close this for now, let me know if this issue pops up again.
