### ISSUE TITLE
Question: Any ideas why Apple don't upgrade their code generation for so long?

### ISSUE THREAD

**Issue by Motti-Shneor** [CFKevinRef/KCOrderedAccessorFix#15]
I'm wondering why Apple added the ordered relations (along with NSOrderedSet) so long ago, but didn't care to fix their horrible crashing generated accessors, and also the terribly broken bindings (of NSArrayControllers, NSTableColumns etc) to ordered relations?

Is this such a tiny thing Apple overlooks it? or is there a "big" reason for this neglect?

If I understand it right, to this moment Everyone using ordered relations MUST use this code to avoid crashes?

**Comment by CFKevinRef** [comment]
I can't speak for Apple's internal priorities, but I'm also amazed that this is still an issue.

It's not completely broken. Accessing unique ordered relationships as a property (`NSOrderedSet`) seems to be fine. The issues lie in the bindings and auto-generated methods, as you mentioned. Maybe most people aren't using these features? Maybe Apple is focusing on Swift collections?

**Comment by Motti-Shneor** [comment]
BTW - I couldn’t conclude reading the issues - is the problem with Xcode 7 solved? I saw commits following this issue, but I didn’t see you close it. 

Is the code safe to use within Xcode 7 (and SDK 10.11) ?

**Comment by CFKevinRef** [comment]
I never got a response on that one, so I'm going to go ahead and close it. I'm not aware of any issues with the current tools and SDKs.
