### ISSUE TITLE
Usage of objc_msgSend needs update for 64-bit architecture

### ISSUE THREAD

**Issue by an0** [CFKevinRef/KCOrderedAccessorFix#5]
According to https://developer.apple.com/library/prerelease/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html#//apple_ref/doc/uid/TP40013501-CH3-SW26.

Your fix is still very useful on iOS 7 since bug 10114310 is till open — I'm totally shocked by Apple's inability to fix this bug:(

Thanks!

**Comment by fatuhoku** [comment]
With Xcode 6 GM, this issue occurs again. Described here: http://stackoverflow.com/q/25852079/590767

**Comment by colasjojo** [comment]
I am having this issue. There are Pull request for this bug, I think. see: http://stackoverflow.com/q/27124512/1670830

**Comment by CFKevinRef** [comment]
Fixed in #10
